# The JSONPath filter expression used to identify which PRs to close.
# The data filtered is the pull request data along with other metadata passed in
# by probot.
# See http://linkremoved/
# `true` will close all PRs.
filters:
  - true

# The message to post to the closed PR.
commentBody: |
  Thanks for your contribution!  Unfortunately, we don't use GitHub pull
  requests as TAL is deprecated. Please see 
  see [README.md](../blob/master/README.md) which provides full
  instructions on how to get involved.

# Whether or not to add a label to the closed PR.
# Default: true
addLabel: true

# The name of the label to add.
# Default: invalid
labelName: autoclosed

# The desired color of the label, in the event that it needs to be created.
# Default: e6e6e6
labelColor: c0ffee