# The JSONPath filter expression used to identify which PRs to close.
# The data filtered is the pull request data along with other metadata passed in
# by probot.
# See http://linkremoved/
# `true` will close all PRs.
filters:
  - true

# The message to post to the closed PR.
commentBody: |
  Thanks for your contribution!  Unfortunately, we don't use GitHub pull
  requests as TAL is deprecated. Please see 
  see [README.md](../blob/master/README.md) which provides full
  instructions on how to get involved.

# Whether to add a label to the closed PR.
addLabel: false